---

  - name: systemd service is installed
    copy: 
      src: ansible-pull.service
      dest: /etc/systemd/system/ansible-pull.service
      owner: root
      group: root
  
  - name: systemd timer is installed
    copy:
      src: ansible-pull.timer
      dest: /etc/systemd/system/ansible-pull.timer
      owner: root
      group: root

  - name: systemd variable file is installed
    template:
      src: env.j2
      dest: /etc/sysconfig/ansible-pull

  - name: timer is enabled
    service:
      name: "{{ item }}"
      state: enabled
    with_items:
      - ansible-pull.service
      - ansible-pull.timer
